<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project functional metadata -->
  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <TargetFrameworks>net462;net47;netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <!-- Package metadata -->
  <PropertyGroup>
    <Title>IX Libraries - Undoable</Title>
    <Description>A library for providing undo/redo functionality to common scenarios.</Description>
  </PropertyGroup>

  <!-- References -->
  <ItemGroup>
    <ProjectReference Include="..\IX.Library\IX.Library.csproj" />
    <ProjectReference Include="..\IX.Undoable\IX.Undoable.csproj" />
  </ItemGroup>

  <!-- Signing -->
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>../Common/ix.framework.strongname.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <!-- Resources -->
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <!-- Text templates -->
  <ItemGroup>
    <None Update="ConcurrentObservableDictionary{TKey,TValue}.ActionsAndFuncs.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ConcurrentObservableDictionary{TKey,TValue}.ActionsAndFuncs.cs</LastGenOutput>
    </None>
    <None Update="ObservableBase.ActionsAndFuncs.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ObservableBase.ActionsAndFuncs.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ConcurrentObservableDictionary{TKey,TValue}.ActionsAndFuncs.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConcurrentObservableDictionary{TKey,TValue}.ActionsAndFuncs.tt</DependentUpon>
    </Compile>
    <Compile Update="ObservableBase.ActionsAndFuncs.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ObservableBase.ActionsAndFuncs.tt</DependentUpon>
    </Compile>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <!-- Services -->
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  
</Project>