<Project>

  <!-- Targets and symbols -->

  <!-- Obsolete -->
  <PropertyGroup Condition="'$(TargetFramework)'=='sl4'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='sl5'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='wp'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='wp7'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='wp75'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='wp8'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='wp81'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='wpa81'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='aspnet50'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='aspnetcore50'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dnxcore50'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dnx'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dnx45'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dnx451'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dnx452'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet50'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet51'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet52'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet53'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet54'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet55'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='dotnet56'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='winrt'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='net10'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net11'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net20'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net35'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net40'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net403'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net45'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net451'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net452'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net46'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net461'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net462'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net47'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net471'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net472'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net48'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.0'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.1'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.2'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.3'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.4'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.5'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.6'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.1'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>


  <PropertyGroup Condition="'$(TargetFramework)'=='net5.0'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net6.0'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net7.0'">
    <TargetFrameworkIsObsolete>true</TargetFrameworkIsObsolete>
  </PropertyGroup>

  <!-- Actual -->
  <PropertyGroup Condition="'$(TargetFramework)'=='net8.0'">
    <TargetFrameworkIs8>true</TargetFrameworkIs8>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net9.0'">
    <TargetFrameworkIs8>true</TargetFrameworkIs8>
    <TargetFrameworkIs9>true</TargetFrameworkIs9>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net10.0'">
    <TargetFrameworkIs8>true</TargetFrameworkIs8>
    <TargetFrameworkIs9>true</TargetFrameworkIs9>
    <TargetFrameworkIs10>true</TargetFrameworkIs10>
  </PropertyGroup>

  <!-- Packability -->
  <PropertyGroup Condition="'$(IsTestProject)'=='true'">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- Language version -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- Deterministic builds -->
  <PropertyGroup>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <!-- Language options -->
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Branding -->
  <PropertyGroup>
    <Authors>Adrian Moș</Authors>
    <Company>Moș A Adrian, PFA</Company>
    <Product>IX Libraries</Product>
    <Copyright>Adrian Moș, 2023</Copyright>
    <PackageProjectUrl>https://github.com/adimosh/IX.Libraries/</PackageProjectUrl>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>