<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <IsIxSourceGenerator>true</IsIxSourceGenerator>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="System.Buffers" Version="4.6.0" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.1" />
    <PackageReference Include="System.Memory" Version="4.6.0" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.0" />
    <PackageReference Include="System.Reflection.Metadata" Version="9.0.1" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.1" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
  </ItemGroup>

</Project>
