<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="StandardExtensions\Globalization\data.zip" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="StandardExtensions\Globalization\data.zip" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IX.Library\IX.Library.csproj" />
    <ProjectReference Include="..\IX.Math\IX.Math.csproj" />
    <ProjectReference Include="..\IX.Observable\IX.Observable.csproj" />
    <ProjectReference Include="..\IX.Undoable\IX.Undoable.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Math\TestData.BasicOperatorsWithRandomNumbers.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>TestData.BasicOperatorsWithRandomNumbers.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Math\TestData.BasicOperatorsWithRandomNumbers.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TestData.BasicOperatorsWithRandomNumbers.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
